//TODO Parameter als string realisieren, parsen

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OPA.GUI;

import OPA.Object.Data;
import OPA.Object.ObjectHandler;
import java.io.File;
import java.util.HashMap;
import javax.swing.ButtonModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Dirk
 */
public class OptionFrame extends javax.swing.JFrame {
    ObjectHandler objHandler;
    FileFilter oopscFilter;
    FileFilter oopsvmFilter;
    FileFilter elseFilter;
    
    HashMap<String,Data> datas;
    HashMap<String,String> cCmd;
    HashMap<String,String> vmCmd;
    /**
     * Creates new form OptionFrame
     */
    public OptionFrame(ObjectHandler objHandler) {
        initComponents();
        this.datas = objHandler.getDatas();
        
        this.cCmd = datas.get("OOPSC_PARAMETERS").getValues();
        this.vmCmd = datas.get("OOPSVM_PARAMETERS").getValues();
        setOOPSCParameters();
        setOOPSVMParameters();
        setFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asBG = new javax.swing.ButtonGroup();
        r2BG = new javax.swing.ButtonGroup();
        r4BG = new javax.swing.ButtonGroup();
        oopscFileChooser = new javax.swing.JFileChooser();
        oopsvmFileChooser = new javax.swing.JFileChooser();
        elseFileChooser = new javax.swing.JFileChooser();
        mainPanel = new javax.swing.JTabbedPane();
        javaFramePanel = new javax.swing.JPanel();
        javaLabel = new javax.swing.JLabel();
        javaExecPathBox = new javax.swing.JCheckBox();
        fromJCButton = new javax.swing.JButton();
        toJCButton = new javax.swing.JButton();
        fromJCText = new javax.swing.JTextField();
        toJCText = new javax.swing.JTextField();
        toVMText = new javax.swing.JTextField();
        fromVMText = new javax.swing.JTextField();
        fromVMButton = new javax.swing.JButton();
        toVMButton = new javax.swing.JButton();
        javaLabel1 = new javax.swing.JLabel();
        javaLabel2 = new javax.swing.JLabel();
        oopscFramePanel = new javax.swing.JPanel();
        oopscLabel = new javax.swing.JLabel();
        toOCPanel = new javax.swing.JButton();
        toOCText = new javax.swing.JTextField();
        ereignissPanel = new javax.swing.JPanel();
        cButton = new javax.swing.JCheckBox();
        lButton = new javax.swing.JCheckBox();
        sButton = new javax.swing.JCheckBox();
        iButton = new javax.swing.JCheckBox();
        stackLabel = new javax.swing.JLabel();
        heapLabel = new javax.swing.JLabel();
        ssButton = new javax.swing.JSpinner();
        hsButton = new javax.swing.JSpinner();
        ereignissLabel = new javax.swing.JLabel();
        oopsvmFramePanel = new javax.swing.JPanel();
        manuellVMPanel = new javax.swing.JPanel();
        manuellVMLabel = new javax.swing.JLabel();
        iVMButton = new javax.swing.JCheckBox();
        mVMButton = new javax.swing.JCheckBox();
        rVMButton = new javax.swing.JCheckBox();
        registerPanel = new javax.swing.JPanel();
        r2Panel = new javax.swing.JPanel();
        r2UpButton = new javax.swing.JRadioButton();
        r2DownButton = new javax.swing.JRadioButton();
        r2NoneButton = new javax.swing.JRadioButton();
        r2Label = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        r4Panel = new javax.swing.JPanel();
        r4UpButton = new javax.swing.JRadioButton();
        r4DownButton = new javax.swing.JRadioButton();
        r4NoneButton = new javax.swing.JRadioButton();
        r4Label = new javax.swing.JLabel();
        assPanel = new javax.swing.JPanel();
        assLabel = new javax.swing.JLabel();
        as1Button = new javax.swing.JRadioButton();
        as2Button = new javax.swing.JRadioButton();
        asnButton = new javax.swing.JRadioButton();
        pathButton = new javax.swing.JCheckBox();

        elseFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setTitle("Optionen");
        setResizable(false);

        javaFramePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javaLabel.setText("JavaC Optionen");

        javaExecPathBox.setSelected(true);
        javaExecPathBox.setText("Java Pfad verwenden");
        javaExecPathBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaExecPathBoxActionPerformed(evt);
            }
        });

        fromJCButton.setText("Von");
        fromJCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromJCButtonActionPerformed(evt);
            }
        });

        toJCButton.setText("zu");
        toJCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toJCButtonActionPerformed(evt);
            }
        });

        fromJCText.setEditable(false);

        toJCText.setEditable(false);

        toVMText.setEditable(false);

        fromVMText.setEditable(false);

        fromVMButton.setText("Von");
        fromVMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromVMButtonActionPerformed(evt);
            }
        });

        toVMButton.setText("zu");
        toVMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toVMButtonActionPerformed(evt);
            }
        });

        javaLabel1.setText("OOPSC");

        javaLabel2.setText("OOPSVM");

        javax.swing.GroupLayout javaFramePanelLayout = new javax.swing.GroupLayout(javaFramePanel);
        javaFramePanel.setLayout(javaFramePanelLayout);
        javaFramePanelLayout.setHorizontalGroup(
            javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javaFramePanelLayout.createSequentialGroup()
                .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(javaLabel)
                    .addComponent(javaExecPathBox))
                .addGap(0, 211, Short.MAX_VALUE))
            .addGroup(javaFramePanelLayout.createSequentialGroup()
                .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javaFramePanelLayout.createSequentialGroup()
                        .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toJCButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fromJCButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromJCText)
                            .addComponent(toJCText)))
                    .addGroup(javaFramePanelLayout.createSequentialGroup()
                        .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toVMButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fromVMButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromVMText)
                            .addComponent(toVMText)))
                    .addGroup(javaFramePanelLayout.createSequentialGroup()
                        .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(javaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(javaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        javaFramePanelLayout.setVerticalGroup(
            javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javaFramePanelLayout.createSequentialGroup()
                .addComponent(javaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(javaExecPathBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(javaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromJCButton)
                    .addComponent(fromJCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toJCButton)
                    .addComponent(toJCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(javaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromVMButton)
                    .addComponent(fromVMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(javaFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toVMButton)
                    .addComponent(toVMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        mainPanel.addTab("JAVA", javaFramePanel);

        oopscFramePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        oopscLabel.setText("OOPSC Optionen");

        toOCPanel.setText("zu");
        toOCPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toOCPanelActionPerformed(evt);
            }
        });

        toOCText.setEditable(false);

        ereignissPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cButton.setText("Kontextanalyse");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        lButton.setText("lexikalische Analyse");
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });

        sButton.setText("syntaktische Analyse");
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });

        iButton.setText("Bezeichner Zuordnung");
        iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });

        stackLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stackLabel.setText("Stack Größe");

        heapLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        heapLabel.setText("Heap Größe");

        ssButton.setValue(100
        );
        ssButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ssButtonStateChanged(evt);
            }
        });

        hsButton.setValue(100);
        hsButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hsButtonStateChanged(evt);
            }
        });

        ereignissLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ereignissLabel.setText("Ergebniss anzeigen");

        javax.swing.GroupLayout ereignissPanelLayout = new javax.swing.GroupLayout(ereignissPanel);
        ereignissPanel.setLayout(ereignissPanelLayout);
        ereignissPanelLayout.setHorizontalGroup(
            ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ereignissPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ereignissPanelLayout.createSequentialGroup()
                        .addGroup(ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ereignissPanelLayout.createSequentialGroup()
                                .addComponent(sButton)
                                .addGap(56, 56, 56)
                                .addComponent(ssButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ereignissPanelLayout.createSequentialGroup()
                                .addComponent(cButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ereignissPanelLayout.createSequentialGroup()
                        .addComponent(lButton)
                        .addGap(64, 64, 64)
                        .addComponent(iButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(ereignissLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ereignissPanelLayout.setVerticalGroup(
            ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ereignissPanelLayout.createSequentialGroup()
                .addComponent(ereignissLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lButton)
                    .addComponent(iButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sButton)
                    .addComponent(ssButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stackLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ereignissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton)
                    .addComponent(hsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout oopscFramePanelLayout = new javax.swing.GroupLayout(oopscFramePanel);
        oopscFramePanel.setLayout(oopscFramePanelLayout);
        oopscFramePanelLayout.setHorizontalGroup(
            oopscFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oopscFramePanelLayout.createSequentialGroup()
                .addComponent(oopscLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(oopscFramePanelLayout.createSequentialGroup()
                .addGroup(oopscFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ereignissPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(oopscFramePanelLayout.createSequentialGroup()
                        .addComponent(toOCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toOCText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        oopscFramePanelLayout.setVerticalGroup(
            oopscFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oopscFramePanelLayout.createSequentialGroup()
                .addComponent(oopscLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ereignissPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(oopscFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toOCPanel)
                    .addComponent(toOCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.addTab("OOPSC", oopscFramePanel);

        manuellVMPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        manuellVMLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        manuellVMLabel.setText("Einstellungen der manuellen Ausführung");

        iVMButton.setText("zeige Instruktionen");
        iVMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iVMButtonActionPerformed(evt);
            }
        });

        mVMButton.setText("zeige Speicher");
        mVMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVMButtonActionPerformed(evt);
            }
        });

        rVMButton.setText("zeige Registersatz");
        rVMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rVMButtonActionPerformed(evt);
            }
        });

        registerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        r2Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        r2BG.add(r2UpButton);
        r2UpButton.setText("von Oben");
        r2UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2UpButtonActionPerformed(evt);
            }
        });

        r2BG.add(r2DownButton);
        r2DownButton.setText("von Unten");
        r2DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2DownButtonActionPerformed(evt);
            }
        });

        r2BG.add(r2NoneButton);
        r2NoneButton.setText("nicht");
        r2NoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2NoneButtonActionPerformed(evt);
            }
        });

        r2Label.setText("Register R2");

        javax.swing.GroupLayout r2PanelLayout = new javax.swing.GroupLayout(r2Panel);
        r2Panel.setLayout(r2PanelLayout);
        r2PanelLayout.setHorizontalGroup(
            r2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(r2PanelLayout.createSequentialGroup()
                .addGroup(r2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(r2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(r2Label))
                    .addComponent(r2UpButton)
                    .addComponent(r2NoneButton)
                    .addComponent(r2DownButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        r2PanelLayout.setVerticalGroup(
            r2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(r2PanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(r2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2UpButton)
                .addGap(1, 1, 1)
                .addComponent(r2DownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2NoneButton)
                .addGap(4, 4, 4))
        );

        registerLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerLabel.setText("Register anzeigen");

        r4Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        r4BG.add(r4UpButton);
        r4UpButton.setText("von Oben");
        r4UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4UpButtonActionPerformed(evt);
            }
        });

        r4BG.add(r4DownButton);
        r4DownButton.setText("von Unten");
        r4DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4DownButtonActionPerformed(evt);
            }
        });

        r4BG.add(r4NoneButton);
        r4NoneButton.setText("nicht");
        r4NoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4NoneButtonActionPerformed(evt);
            }
        });

        r4Label.setText("Register R4");

        javax.swing.GroupLayout r4PanelLayout = new javax.swing.GroupLayout(r4Panel);
        r4Panel.setLayout(r4PanelLayout);
        r4PanelLayout.setHorizontalGroup(
            r4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(r4PanelLayout.createSequentialGroup()
                .addGroup(r4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(r4PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(r4Label))
                    .addComponent(r4UpButton)
                    .addComponent(r4NoneButton)
                    .addComponent(r4DownButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        r4PanelLayout.setVerticalGroup(
            r4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, r4PanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(r4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4UpButton)
                .addGap(1, 1, 1)
                .addComponent(r4DownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4NoneButton)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addComponent(r2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addComponent(registerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(r2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout manuellVMPanelLayout = new javax.swing.GroupLayout(manuellVMPanel);
        manuellVMPanel.setLayout(manuellVMPanelLayout);
        manuellVMPanelLayout.setHorizontalGroup(
            manuellVMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuellVMPanelLayout.createSequentialGroup()
                .addComponent(manuellVMLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(413, 413, 413))
            .addGroup(manuellVMPanelLayout.createSequentialGroup()
                .addGroup(manuellVMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iVMButton)
                    .addComponent(mVMButton)
                    .addComponent(rVMButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manuellVMPanelLayout.setVerticalGroup(
            manuellVMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuellVMPanelLayout.createSequentialGroup()
                .addComponent(manuellVMLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manuellVMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manuellVMPanelLayout.createSequentialGroup()
                        .addComponent(iVMButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mVMButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rVMButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(manuellVMPanelLayout.createSequentialGroup()
                        .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        assPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        assLabel.setText("Assemblierungsläufe");

        asBG.add(as1Button);
        as1Button.setText("1 Durchlauf");
        as1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as1ButtonActionPerformed(evt);
            }
        });

        asBG.add(as2Button);
        as2Button.setText("2 Durchläufe");
        as2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as2ButtonActionPerformed(evt);
            }
        });

        asBG.add(asnButton);
        asnButton.setText("alle Durchläufe");
        asnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout assPanelLayout = new javax.swing.GroupLayout(assPanel);
        assPanel.setLayout(assPanelLayout);
        assPanelLayout.setHorizontalGroup(
            assPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(assLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(assPanelLayout.createSequentialGroup()
                .addComponent(as1Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(as2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(asnButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        assPanelLayout.setVerticalGroup(
            assPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assPanelLayout.createSequentialGroup()
                .addComponent(assLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(assPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as1Button)
                    .addComponent(as2Button)
                    .addComponent(asnButton)))
        );

        javax.swing.GroupLayout oopsvmFramePanelLayout = new javax.swing.GroupLayout(oopsvmFramePanel);
        oopsvmFramePanel.setLayout(oopsvmFramePanelLayout);
        oopsvmFramePanelLayout.setHorizontalGroup(
            oopsvmFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oopsvmFramePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oopsvmFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manuellVMPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(assPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        oopsvmFramePanelLayout.setVerticalGroup(
            oopsvmFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oopsvmFramePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manuellVMPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        mainPanel.addTab("OOPSVM", oopsvmFramePanel);

        pathButton.setSelected(true);
        pathButton.setText("Pfade anzeigen");
        pathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pathButton)
                .addGap(4, 4, 4)
                .addComponent(mainPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromJCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromJCButtonActionPerformed
        oopscFileChooser.setCurrentDirectory(new File (datas.get("OOPS_C_PATH_IN").getStringValue()));
        int returnVal = oopscFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = oopscFileChooser.getSelectedFile().getParent();
            datas.get("OOPS_C_PATH_IN").setValue(filePath);
            fromJCText.setText (filePath);
            

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_fromJCButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        if(cButton.isSelected()){
            cCmd.put("-c", null);
        }else{
            cCmd.remove("-c");
        }
    }//GEN-LAST:event_cButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
                if(lButton.isSelected()){
            cCmd.put("-l", null);
        }else{
            cCmd.remove("-l");
        }
    }//GEN-LAST:event_lButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        if(sButton.isSelected()){
            cCmd.put("-s", null);
        }else{
            cCmd.remove("-s");
        }
    }//GEN-LAST:event_sButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
        if(iButton.isSelected()){
            cCmd.put("-i", null);
        }else{
            cCmd.remove("-i");
        }
    }//GEN-LAST:event_iButtonActionPerformed

    private void ssButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ssButtonStateChanged
        cCmd.put("-ss", ""+ssButton.getValue());
        
    }//GEN-LAST:event_ssButtonStateChanged

    private void hsButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hsButtonStateChanged
        cCmd.put("-hs", ""+hsButton.getValue());
    }//GEN-LAST:event_hsButtonStateChanged

    private void javaExecPathBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaExecPathBoxActionPerformed
        //TODO JAVA Pfad einstellungen
    }//GEN-LAST:event_javaExecPathBoxActionPerformed

    private void toJCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toJCButtonActionPerformed
        elseFileChooser.setCurrentDirectory(new File (datas.get("OOPS_C_PATH_OUT").getStringValue()));
        elseFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = elseFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = elseFileChooser.getSelectedFile().getAbsolutePath();
            datas.get("OOPS_C_PATH_OUT").setValue(filePath);
            toJCText.setText (filePath);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_toJCButtonActionPerformed

    private void toOCPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toOCPanelActionPerformed
        elseFileChooser.setCurrentDirectory(new File (datas.get("OOPS_PROGRAMM_PATH_OUT").getStringValue()));
        int returnVal = oopscFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = elseFileChooser.getSelectedFile().getAbsolutePath();
            datas.get("OOPS_PROGRAMM_PATH_OUT").setValue(filePath);
            toOCText.setText (filePath);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_toOCPanelActionPerformed

    private void fromVMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromVMButtonActionPerformed
        oopsvmFileChooser.setCurrentDirectory(new File (datas.get("OOPS_VM_PATH_IN").getStringValue()));
        int returnVal = oopsvmFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = oopsvmFileChooser.getSelectedFile().getParent();
            datas.get("OOPS_VM_PATH_IN").setValue(filePath);
            fromVMText.setText (filePath);
            

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_fromVMButtonActionPerformed

    private void toVMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toVMButtonActionPerformed
        elseFileChooser.setCurrentDirectory(new File (datas.get("OOPS_VM_PATH_OUT").getStringValue()));
        int returnVal = elseFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = elseFileChooser.getSelectedFile().getAbsolutePath();
            datas.get("OOPS_VM_PATH_OUT").setValue(filePath);
            toVMText.setText (filePath);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_toVMButtonActionPerformed

    private void r2UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2UpButtonActionPerformed
        r2Box();
    }//GEN-LAST:event_r2UpButtonActionPerformed

    private void r4UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4UpButtonActionPerformed
        r4Box();
    }//GEN-LAST:event_r4UpButtonActionPerformed

    private void iVMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iVMButtonActionPerformed
        if(iVMButton.isSelected()){
            vmCmd.put("-i", null);
        }else{
            vmCmd.remove("-i");
        }
    }//GEN-LAST:event_iVMButtonActionPerformed

    private void mVMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVMButtonActionPerformed
        if(mVMButton.isSelected()){
            vmCmd.put("-m", null);
        }else{
            vmCmd.remove("-m");
        }
    }//GEN-LAST:event_mVMButtonActionPerformed

    private void rVMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rVMButtonActionPerformed
        if(rVMButton.isSelected()){
            vmCmd.put("-r", null);
        }else{
            vmCmd.remove("-r");
        }
    }//GEN-LAST:event_rVMButtonActionPerformed

    private void r4DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4DownButtonActionPerformed
        r4Box();
    }//GEN-LAST:event_r4DownButtonActionPerformed

    private void r4NoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4NoneButtonActionPerformed
        r4Box();
    }//GEN-LAST:event_r4NoneButtonActionPerformed

    private void r2DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2DownButtonActionPerformed
        r2Box();
    }//GEN-LAST:event_r2DownButtonActionPerformed

    private void r2NoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2NoneButtonActionPerformed
        r2Box();
    }//GEN-LAST:event_r2NoneButtonActionPerformed

    private void as1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as1ButtonActionPerformed
        asBox();
    }//GEN-LAST:event_as1ButtonActionPerformed

    private void as2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as2ButtonActionPerformed
        asBox();
    }//GEN-LAST:event_as2ButtonActionPerformed

    private void asnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asnButtonActionPerformed
        asBox();
    }//GEN-LAST:event_asnButtonActionPerformed

    private void pathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathButtonActionPerformed
        datas.get("SHORT_NAME").setValue(!pathButton.isSelected());
    }//GEN-LAST:event_pathButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton as1Button;
    private javax.swing.JRadioButton as2Button;
    private javax.swing.ButtonGroup asBG;
    private javax.swing.JRadioButton asnButton;
    private javax.swing.JLabel assLabel;
    private javax.swing.JPanel assPanel;
    private javax.swing.JCheckBox cButton;
    private javax.swing.JFileChooser elseFileChooser;
    private javax.swing.JLabel ereignissLabel;
    private javax.swing.JPanel ereignissPanel;
    private javax.swing.JButton fromJCButton;
    private javax.swing.JTextField fromJCText;
    private javax.swing.JButton fromVMButton;
    private javax.swing.JTextField fromVMText;
    private javax.swing.JLabel heapLabel;
    private javax.swing.JSpinner hsButton;
    private javax.swing.JCheckBox iButton;
    private javax.swing.JCheckBox iVMButton;
    private javax.swing.JCheckBox javaExecPathBox;
    private javax.swing.JPanel javaFramePanel;
    private javax.swing.JLabel javaLabel;
    private javax.swing.JLabel javaLabel1;
    private javax.swing.JLabel javaLabel2;
    private javax.swing.JCheckBox lButton;
    private javax.swing.JCheckBox mVMButton;
    private javax.swing.JTabbedPane mainPanel;
    private javax.swing.JLabel manuellVMLabel;
    private javax.swing.JPanel manuellVMPanel;
    private javax.swing.JFileChooser oopscFileChooser;
    private javax.swing.JPanel oopscFramePanel;
    private javax.swing.JLabel oopscLabel;
    private javax.swing.JFileChooser oopsvmFileChooser;
    private javax.swing.JPanel oopsvmFramePanel;
    private javax.swing.JCheckBox pathButton;
    private javax.swing.ButtonGroup r2BG;
    private javax.swing.JRadioButton r2DownButton;
    private javax.swing.JLabel r2Label;
    private javax.swing.JRadioButton r2NoneButton;
    private javax.swing.JPanel r2Panel;
    private javax.swing.JRadioButton r2UpButton;
    private javax.swing.ButtonGroup r4BG;
    private javax.swing.JRadioButton r4DownButton;
    private javax.swing.JLabel r4Label;
    private javax.swing.JRadioButton r4NoneButton;
    private javax.swing.JPanel r4Panel;
    private javax.swing.JRadioButton r4UpButton;
    private javax.swing.JCheckBox rVMButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JCheckBox sButton;
    private javax.swing.JSpinner ssButton;
    private javax.swing.JLabel stackLabel;
    private javax.swing.JButton toJCButton;
    private javax.swing.JTextField toJCText;
    private javax.swing.JButton toOCPanel;
    private javax.swing.JTextField toOCText;
    private javax.swing.JButton toVMButton;
    private javax.swing.JTextField toVMText;
    // End of variables declaration//GEN-END:variables

    private void r2Box(){
        ButtonModel sel = r2BG.getSelection();
        if(sel.equals(r2UpButton.getModel())){
            vmCmd.put("-f2",null);
            vmCmd.remove("-b2");
        }else if(sel.equals(r2DownButton.getModel())){
            vmCmd.remove("-f2");
            vmCmd.put("-b2",null);
        }else if(sel.equals(r2NoneButton.getModel())){
            vmCmd.remove("-f2");
            vmCmd.remove("-b2");
        }
    }
    private void r4Box(){
        ButtonModel sel = r4BG.getSelection();
        if(sel.equals(r4UpButton.getModel())){
            vmCmd.put("-f4",null);
            vmCmd.remove("-b4");
        }else if(sel.equals(r4DownButton.getModel())){
            vmCmd.remove("-f4");
            vmCmd.put("-b4",null);
        }else if(sel.equals(r4NoneButton.getModel())){
            vmCmd.remove("-f4");
            vmCmd.remove("-b4");
        }
    }
    
    private void asBox(){
        Data data = datas.get("PARAM_VM_C");
        ButtonModel sel = asBG.getSelection();
        if(sel.equals(as1Button.getModel())){
            data.setValue("1");
        }else if(sel.equals(as2Button.getModel())){
            data.setValue("2");
        }else{
            data.setValue("ALL");
        }
    }
    
    private void setFilter(){
        final String oopscName = datas.get("OOPS_COMPILER_NAME").getStringValue();
        FileFilter filter;
        filter =  new FileFilter() {
                @Override
                public boolean accept(File f) {
                    return (f.getName().equals(oopscName+".java") || f.isDirectory());
                }
                @Override
                public String getDescription() {
                        return oopscName+".java";
                }
            };
        oopscFileChooser.setFileFilter(filter);
        final String oopsvmName = datas.get("OOPS_VM_NAME").getStringValue();
        filter =  new FileFilter() {
                @Override
                public boolean accept(File f) {
                    return (f.getName().equals(oopsvmName+".java") || f.isDirectory());
                }
                @Override
                public String getDescription() {
                        return oopsvmName+".java";
                }
            };
        oopsvmFileChooser.setFileFilter(filter);
    }

    private void setOOPSCParameters() {
        
        pathButton.setSelected(datas.get("SHORT_NAME").getBooleanValue());
        
        toOCText.setText(datas.get("OOPS_PROGRAMM_PATH_OUT").getStringValue());
        fromJCText.setText(datas.get("OOPS_C_PATH_IN").getStringValue());
        toJCText.setText(datas.get("OOPS_C_PATH_OUT").getStringValue());
        fromVMText.setText(datas.get("OOPS_VM_PATH_IN").getStringValue());
        toVMText.setText(datas.get("OOPS_VM_PATH_OUT").getStringValue());
        
        String value = cCmd.get("-c");
            cButton.setSelected(value != null);
        value = cCmd.get("-s");
            sButton.setSelected(value != null);
        value = cCmd.get("-i");
            iButton.setSelected(value != null);
        value = cCmd.get("-l");
            lButton.setSelected(value != null);        
        value = cCmd.get("-hs");
            hsButton.setValue((value!=null)?Integer.parseInt(value) :100);
        value = cCmd.get("-ss");
            ssButton.setValue((value!=null)?Integer.parseInt(value) :100);
    }

    private void setOOPSVMParameters() {
        String value = vmCmd.get("-i");
            iVMButton.setSelected(value != null);
        value = vmCmd.get("-m");
            mVMButton.setSelected(value != null);
        value = vmCmd.get("-r");
            rVMButton.setSelected(value != null);
            //TODO richtige parameter finden
            
        value = vmCmd.get("-2");
        if(value != null){
            asBG.setSelected(as2Button.getModel(), true);
        }else{
            value = vmCmd.get("-1");
            if(value != null){
                asBG.setSelected(as1Button.getModel(), true);
            }else{
                asBG.setSelected(asnButton.getModel(), true);
            }
        }
        
        value = vmCmd.get("-f2");
        if(value != null){
            asBG.setSelected(r2UpButton.getModel(), true);
        }else{
            value = vmCmd.get("-b2");
            if(value != null){
                asBG.setSelected(r2DownButton.getModel(), true);
            }else{
                asBG.setSelected(r2NoneButton.getModel(), true);
            }
        }
        
        value = vmCmd.get("-f4");
        if(value != null){
            asBG.setSelected(r2UpButton.getModel(), true);
        }else{
            value = vmCmd.get("-b4");
            if(value != null){
                asBG.setSelected(r2DownButton.getModel(), true);
            }else{
                asBG.setSelected(r2NoneButton.getModel(), true);
            }
        }
    }
}
